### ISSUE TITLE
Error with import

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC#11]
Trying to run the develop branch I'm getting this error:

```
error: A hook (`controllers`) failed to load!
error: `include-all` attempted to `require(C:\Dev\GALA-TAPICC-server\dev\trunk\src\api\controllers\AssetController.ts)`, but an error occurred::
Details:C:\Dev\GALA-TAPICC-server\dev\trunk\src\api\controllers\AssetController.ts:7
import express = require('express');
^^^^^^
```
It seems `import` is not supported with all versions of Node. Is there some minimal version required here?

Thanks

**Comment by Alino** [comment]
when I run ```node --version```
I get ```v9.3.0```

So I would say v9.3.0 is minimal version.

**Comment by ysavourel** [comment]
It seems even 9.9.0 (current latest) does not support `import` by default.
See https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import

Maybe we could use older but more backward compatible statements?

**Comment by Alino** [comment]
can you please describe the steps, how are you trying to run the server, what commands do you use?

maybe instead of ```sails lift``` you can try ```npm start``` which uses ts-node instead of node.
ts-node supports typescript, and typescript supports ecmascript6 statements such as import, export

**Comment by ysavourel** [comment]
I've followed the readme:
`npm install`
then `sails lift`
(after installing Sails)

But it looks like you've updated the readme, and indeed with `npm start` the server starts and http://localhost:1337 is running.
Thanks.
