### ISSUE TITLE
Several ways to do the same thing

### ISSUE THREAD

**Issue by ysavourel** [GALAglobal/TAPICC#14]
I realize this is an early version and you may have already plan to change things, but I thought any input could be helpful:

I've noticed that the current API offers several way to access the same resources. For example you can get the asset 123 of the job 456 with `GET /job/456/asset/123` and with `GET /asset/123`.

I'm not sure this is a good or bad idea:
* The developers have to implement, maintain and test more code,
* The users have different ways to do the same thing, which from my experience may not be a good idea.
* It also forces the ID of the assets, tasks, etc. to be globally unique, which may or may not be OK.
* It also allows access to the deeper resources with only the knowledge of the ID of that resources, not knowing, for example, the job ID. And that may be an advantage.

I guess it would be good to have a discussion about the pros and cons for this in the WG.

**Comment by Alino** [comment]
Good points, as you say, this should be discussed. I am not sure either about this.

**Comment by Alino** [comment]
Kamino closed and cloned this issue to GALAglobal/TAPICC-API-implementation
