### ISSUE TITLE
separating the API implementation to another github repository

### ISSUE THREAD

**Issue by Alino** [GALAglobal/TAPICC#21]
I have created this github repository
https://github.com/Alino/TAPICC-API-implementation

I would like to transfer ownership to GALAglobal but I need permission to create repositories in GALAglobal.

The reason why I did this separation is because I didn't want to pollute github issues for this repository with user stories and bugs/issues related to the API implementation.

**Comment by DavidFatDavidF** [comment]
Hi Alex,

I transferred the repo under the GALA organization.
Please finish set up:

1) The same licence
2) the CLA assistant set up to prevent PRs from people who didn't sign the
legal

Cheers and thanks
dF

Dr. David Filip
===========
Convenor, JTC 1/SC 42/SG 2 Trustworthiness of AI | National mirror chair,
NSAI TC 02/SC 18 AI | Head of the Irish National Delegation, ISO/IEC JTC
1/SC 42 AI | Chair & Editor, OASIS XLIFF OMOS TC  | Secretary & Lead
Editor, OASIS XLIFF TC | NSAI expert to ISO/IEC JTC 1/SC 38 Cloud
Computing, ISO TC 37/SC 3 Terminology management, SC 4 Language resources,
SC 5 Language technology
Moravia Research Fellow
ADAPT Centre
KDEG, Trinity College Dublin
Mobile: +420-777-218-122



On Mon, Jul 9, 2018 at 4:07 PM, Alexander Sadovsky <notifications@github.com

**Comment by Alino** [comment]
Hi David,

only I can transfer the repo under GALA successfully including data such as issues created for that repo.
I have button in the settings of that repo
![image](https://user-images.githubusercontent.com/763194/42557794-bb2886b4-84ef-11e8-894d-6b5c1fd547b0.png)
All I need is permissions to create repos under GALAglobal.

Could you please remove this repo https://github.com/GALAglobal/TAPICC-API-implementation
and give me the rights for GALAglobal, so I can transfer the repo correctly?

Thank you
Alex

**Comment by laurabrandon** [comment]
Hi Alex,

I think I need to make you a “member” of the GALA organization on Github. Members (and not just owners) now have the ability to create repos. You should get an invitation from GitHub shortly.

I can remove the repo that you mention – David is that OK by you?

Thanks,
Allison

**Comment by Alino** [comment]
Thank you Laura, I have accepted the invitation few minutes ago from Allison.
What's left is removing this repo https://github.com/GALAglobal/TAPICC-API-implementation

**Comment by Alino** [comment]
the transfer is done.
Thanks everyone
